2025-05-16T09:19:36.848Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:36.848Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:36.849Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:37.220Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:37.220Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:37.222Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:38.149Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:38.150Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-16T09:19:38.150Z [ERROR]: API call error: TypeError: Cannot read properties of null (reading 'data')
2025-05-19T04:12:13.303Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
2025-05-19T04:12:13.306Z [ERROR]: File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747627933128-9263284a9be07.py", line 4
    return ./scorers/score1.py:score
           ^
SyntaxError: invalid syntax
2025-05-19T04:12:13.315Z [ERROR]: Error running Python script: SyntaxError: invalid syntax
Stack Trace: Error: SyntaxError: invalid syntax
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1017, in get_code
    File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747627933128-9263284a9be07.py", line 4
      return ./scorers/score1.py:score
             ^
2025-05-19T04:12:13.316Z [ERROR]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747627933129-f734bde20ae1f.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747627933129-f734bde20ae1f.json'
2025-05-19T04:12:13.316Z [ERROR]: Error executing Python code: Error: Error running Python script: SyntaxError: invalid syntax
Stack Trace: Error: SyntaxError: invalid syntax
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1017, in get_code
    File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747627933128-9263284a9be07.py", line 4
      return ./scorers/score1.py:score
             ^
2025-05-19T04:13:18.883Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747627998718-f6f54b5ca15e8.py", line 4
    return ./scorers/score1.py:score
           ^
SyntaxError: invalid syntax
2025-05-19T04:13:18.892Z [ERROR]: Error running Python script: SyntaxError: invalid syntax
Stack Trace: Error: SyntaxError: invalid syntax
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1017, in get_code
    File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747627998718-f6f54b5ca15e8.py", line 4
      return ./scorers/score1.py:score
             ^
2025-05-19T04:13:18.893Z [ERROR]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747627998719-b8dcaed4c970b.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747627998719-b8dcaed4c970b.json'
2025-05-19T04:13:18.893Z [ERROR]: Error executing Python code: Error: Error running Python script: SyntaxError: invalid syntax
Stack Trace: Error: SyntaxError: invalid syntax
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1017, in get_code
    File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747627998718-f6f54b5ca15e8.py", line 4
      return ./scorers/score1.py:score
             ^
2025-05-19T04:14:14.684Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747628054552-d0678a2dbadee.py", line 4
    return ./scorers/score1.py:score
           ^
SyntaxError: invalid syntax
2025-05-19T04:14:14.695Z [ERROR]: Error running Python script: SyntaxError: invalid syntax
Stack Trace: Error: SyntaxError: invalid syntax
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 936, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1074, in get_code
    File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747628054552-d0678a2dbadee.py", line 4
      return ./scorers/score1.py:score
             ^
2025-05-19T04:14:14.696Z [ERROR]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747628054552-d71bf0327a0de.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747628054552-d71bf0327a0de.json'
2025-05-19T04:14:14.696Z [ERROR]: Error executing Python code: Error: Error running Python script: SyntaxError: invalid syntax
Stack Trace: Error: SyntaxError: invalid syntax
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 936, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1074, in get_code
    File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "C:\Users\USER\AppData\Local\Temp\temp-python-code-1747628054552-d0678a2dbadee.py", line 4
      return ./scorers/score1.py:score
             ^
2025-05-19T07:21:17.983Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
  File "D:\graduate\prompt_alignment\tests\test2.py", line 8, in generate_tests
    { "type": "icontains", "value": "������" | "�D����",  "weight": 3 },
TypeError: unsupported operand type(s) for |: 'str' and 'str'
2025-05-19T07:21:17.989Z [ERROR]: Error running Python script: TypeError: unsupported operand type(s) for |: 'str' and 'str'
Stack Trace: Error: TypeError: unsupported operand type(s) for |: 'str' and 'str'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "D:\graduate\prompt_alignment\tests\test2.py", line 8, in generate_tests
      { "type": "icontains", "value": "������" | "�D����",  "weight": 3 },
2025-05-19T07:23:14.074Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\tests\\test3.py'
2025-05-19T07:23:14.082Z [ERROR]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\tests\\test3.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\tests\\test3.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-19T07:27:23.774Z [ERROR]: Could not identify provider: [1mgpt-4o-mini[22m.

[37mPlease check your configuration and ensure the provider is correctly specified.[39m
[37m[39m
[37mFor more information on supported providers, visit:[39m [36mhttps://promptfoo.dev/docs/providers/[39m
2025-05-19T07:27:23.840Z [ERROR]: Could not identify provider: [1mgpt-4o-mini[22m.

[37mPlease check your configuration and ensure the provider is correctly specified.[39m
[37m[39m
[37mFor more information on supported providers, visit:[39m [36mhttps://promptfoo.dev/docs/providers/[39m
2025-05-19T07:27:23.871Z [ERROR]: Could not identify provider: [1mgpt-4o-mini[22m.

[37mPlease check your configuration and ensure the provider is correctly specified.[39m
[37m[39m
[37mFor more information on supported providers, visit:[39m [36mhttps://promptfoo.dev/docs/providers/[39m
2025-05-21T07:40:42.126Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
2025-05-21T07:40:42.128Z [ERROR] [pythonUtils.js:107]: return method_to_call(*args)
TypeError: run() takes 0 positional arguments but 3 were given
2025-05-21T07:40:42.132Z [ERROR] [pythonUtils.js:142]: Error running Python script: TypeError: run() takes 0 positional arguments but 3 were given
Stack Trace: Error: TypeError: run() takes 0 positional arguments but 3 were given
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
2025-05-21T07:40:42.132Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813241943-19cad42ce2c8d.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813241943-19cad42ce2c8d.json'
2025-05-21T07:40:42.369Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
TypeError: run() takes 0 positional arguments but 3 were given
2025-05-21T07:40:42.381Z [ERROR] [pythonUtils.js:142]: Error running Python script: TypeError: run() takes 0 positional arguments but 3 were given
Stack Trace: Error: TypeError: run() takes 0 positional arguments but 3 were given
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
2025-05-21T07:40:42.383Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813242178-a7c7dc64eec62.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813242178-a7c7dc64eec62.json'
2025-05-21T07:40:42.436Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
TypeError: run() takes 0 positional arguments but 3 were given
2025-05-21T07:40:42.449Z [ERROR] [pythonUtils.js:142]: Error running Python script: TypeError: run() takes 0 positional arguments but 3 were given
Stack Trace: Error: TypeError: run() takes 0 positional arguments but 3 were given
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
2025-05-21T07:40:42.450Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813242276-27f8d2be1f5d7.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813242276-27f8d2be1f5d7.json'
2025-05-21T07:40:49.742Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
TypeError: run() takes 0 positional arguments but 3 were given
2025-05-21T07:40:49.751Z [ERROR] [pythonUtils.js:142]: Error running Python script: TypeError: run() takes 0 positional arguments but 3 were given
Stack Trace: Error: TypeError: run() takes 0 positional arguments but 3 were given
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
2025-05-21T07:40:49.752Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813249539-1846e76da8a67.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813249539-1846e76da8a67.json'
2025-05-21T07:40:49.976Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
TypeError: run() takes 0 positional arguments but 3 were given
2025-05-21T07:40:49.987Z [ERROR] [pythonUtils.js:142]: Error running Python script: TypeError: run() takes 0 positional arguments but 3 were given
Stack Trace: Error: TypeError: run() takes 0 positional arguments but 3 were given
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
2025-05-21T07:40:49.988Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813249819-478e495123af3.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813249819-478e495123af3.json'
2025-05-21T07:40:50.036Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
    return method_to_call(*args)
TypeError: run() takes 0 positional arguments but 3 were given
2025-05-21T07:40:50.046Z [ERROR] [pythonUtils.js:142]: Error running Python script: TypeError: run() takes 0 positional arguments but 3 were given
Stack Trace: Error: TypeError: run() takes 0 positional arguments but 3 were given
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
2025-05-21T07:40:50.047Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813249895-d97e05b77543f.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813249895-d97e05b77543f.json'
2025-05-21T07:45:02.781Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:02.784Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:02.792Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
2025-05-21T07:45:02.793Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:02.794Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502574-5611c1cb2718a.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502574-5611c1cb2718a.json'
2025-05-21T07:45:02.818Z [ERROR] [pythonUtils.js:107]: File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:02.819Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:02.820Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502599-f4b7469c2650e.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502599-f4b7469c2650e.json'
2025-05-21T07:45:02.828Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at Socket.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:164:17)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:02.828Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502625-44024deeace0e.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502625-44024deeace0e.json'
2025-05-21T07:45:02.837Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:02.837Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at Socket.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:164:17)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:02.838Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502647-78435160ebb35.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502647-78435160ebb35.json'
2025-05-21T07:45:03.016Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:03.029Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:03.030Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502850-1d5fc507a9567.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502850-1d5fc507a9567.json'
2025-05-21T07:45:03.039Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:03.071Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:03.072Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:03.073Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502869-bf16c3f77bff.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502869-bf16c3f77bff.json'
2025-05-21T07:45:03.093Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at Socket.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:164:17)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:03.094Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502888-3de30005d9493.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813502888-3de30005d9493.json'
2025-05-21T07:45:03.194Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:03.208Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:03.209Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813503003-ab55ed30b517a.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813503003-ab55ed30b517a.json'
2025-05-21T07:45:03.227Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:03.239Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:03.239Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813503043-9c7274838561a.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813503043-9c7274838561a.json'
2025-05-21T07:45:03.433Z [ERROR] [pythonUtils.js:107]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
2025-05-21T07:45:03.444Z [ERROR] [pythonUtils.js:142]: Error running Python script: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
Stack Trace: Error: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\graduate\\prompt_alignment\\scorers\\scoring.py'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 18, in call_method
      spec.loader.exec_module(script_module)
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
2025-05-21T07:45:03.445Z [ERROR] [pythonUtils.js:153]: Error removing C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813503274-f30a062cf1f3c.json: Error: ENOENT: no such file or directory, unlink 'C:\Users\USER\AppData\Local\Temp\promptfoo-python-output-json-1747813503274-f30a062cf1f3c.json'
2025-05-27T02:59:19.202Z [ERROR]: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
2025-05-27T02:59:19.215Z [ERROR]: return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
2025-05-27T02:59:19.216Z [ERROR]: File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'user_prompt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
    result = call_method(script_path, method_name, *data)
  File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
2025-05-27T02:59:19.218Z [ERROR]: return method_to_call(*args)
  File "D:\graduate\Promptfoo-LLM\tests\testcases.py", line 9, in generate_tests
    "user_prompt": row["user_prompt"]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
2025-05-27T02:59:19.239Z [ERROR]: return self._get_value(key)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 1237, in _get_value
2025-05-27T02:59:19.239Z [ERROR]: loc = self.index.get_loc(label)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'user_prompt'
2025-05-27T02:59:19.306Z [ERROR]: Error running Python script: KeyError: 'user_prompt'
Stack Trace: Error: KeyError: 'user_prompt'
    at PythonShell.parseError (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:303:21)
    at terminateIfNeeded (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:193:32)
    at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\node_modules\python-shell\index.js:185:13)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    --Python Traceback: --
    File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
      return self._engine.get_loc(casted_key)
    File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
    File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
    File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'user_prompt'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 39, in <module>
      result = call_method(script_path, method_name, *data)
    File "C:\Users\USER\AppData\Roaming\npm\node_modules\promptfoo\dist\src\python\wrapper.py", line 28, in call_method
      return method_to_call(*args)
    File "D:\graduate\Promptfoo-LLM\tests\testcases.py", line 9, in generate_tests
      "user_prompt": row["user_prompt"]
    File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
      return self._get_value(key)
    File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\series.py", line 1237, in _get_value
      loc = self.index.get_loc(label)
    File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
      raise KeyError(key) from err
